stages:
  - test
  - build
  - deploy

default:
  image: gradle:8.7-jdk21

.standard-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

unit-test-job:
  stage: test
  extends:
    - .standard-rules
  coverage: '/    - Complexity Coverage: ([0-9.]+)%/'
  script:
    - gradle clean test
    - gradle jacocoTestCoverageVerification

lint-test-job:
  stage: test
  extends:
    - .standard-rules
  script:
    - gradle checkstyleMain

build-frontend-job:
  stage: build
  extends:
    - .standard-rules
  image: node:20
  script:
    - cd client
    - npm ci
    - npm run build -if--present
    - cd ..
  artifacts:
    when: on_success
    expire_in: 5 minutes
    paths:
      - client/dist

build-backend-job:
  stage: build
  script:
    - gradle clean build -Pversion=$CI_PIPELINE_ID.$CI_COMMIT_BRANCH.$CI_COMMIT_SHORT_SHA
  artifacts:
    when: on_success
    name: $CI_JOB_NAME
    paths:
      - domain/build/libs/*.jar
      - api/build/libs/*.jar
      - persistence/build/libs/*.jar
    expire_in: 5 minutes
