stages:
  - build
  - test
  - deploy

default:
  image: gradle:8.7-jdk21

.standard-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

unit-test-job:
  stage: test
  extends:
    - .standard-rules
  coverage: '/Complexity Coverage: (\d+\.\d+\%)/'
  script:
    - gradle clean test
    - gradle jacocoTestCoverageVerification

lint-test-job:
  stage: test
  extends:
    - .standard-rules
  script:
    - gradle checkstyleMain

build-frontend-job:
  stage: build
  extends:
    - .standard-rules
  image: node:20
  script:
    - cd client
    - npm ci
    - npm run build -if--present
    - cd ..
  artifacts:
    when: on_success
    expire_in: 1 minute
    paths:
      - client/dist

build-backend-zip:
  stage: build
  script:
    - gradle distZip -Pversion=$CI_PIPELINE_ID.$CI_COMMIT_BRANCH.$CI_COMMIT_SHORT_SHA
    - cp $CI_PROJECT_DIR/api/build/distributions/*.zip $CI_PROJECT_DIR/modelr.zip
  artifacts:
    when: on_success
    name: $CI_JOB_NAME
    paths:
      - $CI_PROJECT_DIR/*.zip
    expire_in: 5 minutes
