version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'springuser', '-p$$SPRING_DATASOURCE_PASSWORD' ]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s56ntJp!?
      MYSQL_DATABASE: individual_project
      MYSQL_USER: springuser
      MYSQL_PASSWORD: s56ntJp!?


  web-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
         condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/individual_project
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: s56ntJp!?
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver


  web-frontend:
    build:
      context: ./client
      dockerfile: frontend.dockerfile
    ports:
      - "4173:4173"
    environment:
      BACKEND_SERVER: http://web-backend:8080


