# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Kotlin project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Kotlin CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MIN_CODE_COVERAGE: 95

jobs:

  test-backend:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: perform unit-tests
        run: ./gradlew clean test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: domain/build/reports/jacoco/test/jacocoTestReport.csv
          fail-if-coverage-less-than: 95

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: 'commit badge'
          add: '*.svg'

      - name: Check Style
        run: ./gradlew checkStyleMain

  build-backend:

    needs: test-backend

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOs-latest ]
    runs-on: ${{matrix.os}}

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 8.7

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-package
        path: |
          domain/build/libs/domain-plain.jar
          persistence/build/libs/persistence-plain.jar
          api/build/libs/api.jar app.jar

  build-frontend:

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOs-latest ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Build application
        working-directory: ./client
        run: npm run build --if-present

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
